name: CI
on:
  pull_request:
    branches: ["main"]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@nextest
      - uses: actions/cache@v4
        with:
          path: | 
            ~/.cargo
            target/
          key: ${{runner.os}}-cargo-${{hashFiles('Cargo.lock')}}
      - run: cargo nextest run
  doc-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: | 
            ~/.cargo
            target/
          key: ${{runner.os}}-cargo-${{hashFiles('Cargo.lock')}}
      - run: cargo test --doc
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: | 
            ~/.cargo
            target/
          key: ${{runner.os}}-cargo-${{hashFiles('Cargo.lock')}}
      - run: cargo fmt --check
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: | 
            ~/.cargo
            target/
          key: ${{runner.os}}-cargo-${{hashFiles('Cargo.lock')}}
      - run: cargo clippy -- -D warnings
  all-systems-pass:
    needs: [lint,format,doc-test,test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
